AWSTemplateFormatVersion: 2010-09-09
Description: This Template will create the supporting infrastructure for the ElectricEye-ChatOps module to send Security Hub findings to Slack
Metadata:
  License: GPL-3.0
Parameters:
  WebHookParameterName:
    Type: String
    Description: The names of the SSM Parameter that contains the Slack App Webhook URL for ElectricEye-ChatOps
    Default: slackwebhookParam
  SeverityLevel:
    Type: CommaDelimitedList
    Description: Choose among CRITICAL,HIGH,MEDIUM
    Default: 'CRITICAL,HIGH,MEDIUM'  
Resources:
  ElectricEyeChatOpsRRLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ElectricEye-ChatOps-Slack
      Description: Sends the results of high-severity ElectricEye findings to a Slack Channel - Managed by CloudFormation
      Handler: index.lambda_handler
      MemorySize: 256
      Role: !GetAtt ElectricEyeChatOpsExecRole.Arn
      Runtime: python3.7
      Timeout: 60
      Environment:
        Variables:
          SLACK_WEBHOOK_PARAMETER: !Ref WebHookParameterName
      Code:
        ZipFile: |
          import os
          import boto3
          import json
          import urllib3
          import logging

          logger = logging.getLogger()
          logger.setLevel(logging.INFO)

          def lambda_handler(event, context):
              # create ssm client
              ssm = boto3.client('ssm')
              # create env var for SSM Parameter containing Slack Webhook URL
              webhookParam = os.environ['SLACK_WEBHOOK_PARAMETER']
              http = urllib3.PoolManager()
              # retrieve slack webhook from SSM
              slack_hooks = []
              try:
                  response = ssm.get_parameter(Name=webhookParam,WithDecryption=True)
                  response_object = str(response['Parameter']['Value'])
                  response_object_dict= json.loads(response_object)
                  slack_hooks = response_object_dict.get('slack_hooks')
              except Exception as e:
                  logger.exception(e)
              slackHeaders = {'Content-Type': 'application/json'}
              for findings in event['detail']['findings']:
                  severityLabel = str(findings['Severity']['Label'])
                  electricEyeCheck = str(findings['Title'])
                  awsAccountId = str(findings['AwsAccountId'])
                  for resources in findings['Resources']:
                      resourceId = str(resources['Id'])
              slackMessage = 'A new ' + severityLabel + ' severity finding for ' + resourceId + ' in acccount ' + awsAccountId + ' has been created in Security Hub due to failing the check: ' + electricEyeCheck
              message = {'text': slackMessage}
              for webhook in slack_hooks:
                  status=http.request('POST', slackWebhook,  headers=slackHeaders, body=json.dumps(message).encode('utf-8'))
                  logger.info(status)

  ElectricEyeChatOpsExecRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
      - PolicyName: ElectricEye-ChatOps-RolePolicy
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action:
            - ssm:GetParameter
            - ssm:GetParameters
            Resource: '*'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal: { Service: lambda.amazonaws.com }
          Action:
          - sts:AssumeRole
  ElectricEyeChatOpsEventRule: 
    Type: AWS::Events::Rule
    Properties: 
      Name: ElectricEye-ChatOps-CWE
      Description: "Sends the results of high-severity ElectricEye findings to a Slack Channel via Lambda - Managed by CloudFormation"
      EventPattern: 
        source:
          - aws.securityhub
        detail-type:
          - Security Hub Findings - Imported
        detail:
          findings:
            ProductFields:
              Product Name:
                - Day2SecurityBot
            Severity:
              Label: !Ref SeverityLevel
      State: "ENABLED"
      Targets: 
        - 
          Arn: 
            Fn::GetAtt: 
              - "ElectricEyeChatOpsRRLambdaFunction"
              - "Arn"
          Id: "ElectricEye_ChatOps_CWE"
  ElectricEyeChatOpsRRCWEPermissions: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: 
        Ref: "ElectricEyeChatOpsRRLambdaFunction"
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: 
        Fn::GetAtt: 
          - "ElectricEyeChatOpsEventRule"
          - "Arn"